package oracle.project.AssetManagement.uiview;

import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 18 13:02:33 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AssetManagementAM1Impl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AssetManagementAM1Impl() {
    }

    /**
     * Container's getter for UserObject1.
     * @return UserObject1
     */
    public ViewObjectImpl getUserObject1() {
        return (ViewObjectImpl)findViewObject("UserObject1");
    }

    /**
     * Container's getter for UserUpdatable1.
     * @return UserUpdatable1
     */
    public ViewObjectImpl getUserUpdatable1() {
        return (ViewObjectImpl)findViewObject("UserUpdatable1");
    }

    /**
     * Container's getter for Transaction1.
     * @return Transaction1
     */
    public ViewObjectImpl getTransaction1() {
        return (ViewObjectImpl)findViewObject("Transaction1");
    }

    /**
     * Container's getter for UserUpdatable2.
     * @return UserUpdatable2
     */
    public ViewObjectImpl getUserUpdatable2() {
        return (ViewObjectImpl)findViewObject("UserUpdatable2");
    }

    /**
     * Container's getter for Transaction2.
     * @return Transaction2
     */
    public ViewObjectImpl getTransaction2() {
        return (ViewObjectImpl)findViewObject("Transaction2");
    }

    /**
     * Container's getter for Question1.
     * @return Question1
     */
    public ViewObjectImpl getQuestion1() {
        return (ViewObjectImpl)findViewObject("Question1");
    }

    /**
     * Container's getter for Monthly1.
     * @return Monthly1
     */
    public ViewObjectImpl getMonthly1() {
        return (ViewObjectImpl)findViewObject("Monthly1");
    }

    /**
     * Container's getter for TransactionVL.
     * @return TransactionVL
     */
    public ViewLinkImpl getTransactionVL() {
        return (ViewLinkImpl)findViewLink("TransactionVL");
    }


    /**
     * Container's getter for LovStatus1.
     * @return LovStatus1
     */
    public ViewObjectImpl getLovStatus1() {
        return (ViewObjectImpl)findViewObject("LovStatus1");
    }

    /**
     * Container's getter for LovTypeV1.
     * @return LovTypeV1
     */
    public ViewObjectImpl getLovTypeV1() {
        return (ViewObjectImpl)findViewObject("LovTypeV1");
    }

    /**
     * Container's getter for ViewObj1.
     * @return ViewObj1
     */
    public ViewObjectImpl getViewObj1() {
        return (ViewObjectImpl)findViewObject("ViewObj1");
    }

    /**
     * Container's getter for MonthlyAnalyticsV1.
     * @return MonthlyAnalyticsV1
     */
    public MonthlyAnalyticsVVOImpl getMonthlyAnalyticsV1() {
        return (MonthlyAnalyticsVVOImpl)findViewObject("MonthlyAnalyticsV1");
    }

    /**
     * Container's getter for MonthlyAnalyticsDebtV1.
     * @return MonthlyAnalyticsDebtV1
     */
    public MonthlyAnalyticsDebtVVOImpl getMonthlyAnalyticsDebtV1() {
        return (MonthlyAnalyticsDebtVVOImpl)findViewObject("MonthlyAnalyticsDebtV1");
    }

    /**
     * Container's getter for MonthlyAnalticsBookOV1.
     * @return MonthlyAnalticsBookOV1
     */
    public MonthlyAnalticsBookOVVOImpl getMonthlyAnalticsBookOV1() {
        return (MonthlyAnalticsBookOVVOImpl)findViewObject("MonthlyAnalticsBookOV1");
    }

    /**
     * Container's getter for MonthlyAnalyticsBookLV1.
     * @return MonthlyAnalyticsBookLV1
     */
    public MonthlyAnalyticsBookLVVOImpl getMonthlyAnalyticsBookLV1() {
        return (MonthlyAnalyticsBookLVVOImpl)findViewObject("MonthlyAnalyticsBookLV1");
    }

    /**
     * Container's getter for YearlyAnalyticsDebtV1.
     * @return YearlyAnalyticsDebtV1
     */
    public YearlyAnalyticsDebtVVOImpl getYearlyAnalyticsDebtV1() {
        return (YearlyAnalyticsDebtVVOImpl)findViewObject("YearlyAnalyticsDebtV1");
    }

    /**
     * Container's getter for YearlyAnalyticsBookLV1.
     * @return YearlyAnalyticsBookLV1
     */
    public YearlyAnalyticsBookLVVOImpl getYearlyAnalyticsBookLV1() {
        return (YearlyAnalyticsBookLVVOImpl)findViewObject("YearlyAnalyticsBookLV1");
    }

    /**
     * Container's getter for YearlyAnalyticsBookOV1.
     * @return YearlyAnalyticsBookOV1
     */
    public YearlyAnalyticsBookOVVOImpl getYearlyAnalyticsBookOV1() {
        return (YearlyAnalyticsBookOVVOImpl)findViewObject("YearlyAnalyticsBookOV1");
    }

    /**
     * Container's getter for YearlyAnalyticsLentV1.
     * @return YearlyAnalyticsLentV1
     */
    public YearlyAnalyticsLentVVOImpl getYearlyAnalyticsLentV1() {
        return (YearlyAnalyticsLentVVOImpl)findViewObject("YearlyAnalyticsLentV1");
    }

    /**
     * Container's getter for YearlyAnalyticsV1.
     * @return YearlyAnalyticsV1
     */
    public YearlyAnalyticsVVOImpl getYearlyAnalyticsV1() {
        return (YearlyAnalyticsVVOImpl)findViewObject("YearlyAnalyticsV1");
    }

    /**
     * Container's getter for MonthsOFYear1.
     * @return MonthsOFYear1
     */
    public ViewObjectImpl getMonthsOFYear1() {
        return (ViewObjectImpl)findViewObject("MonthsOFYear1");
    }

    /**
     * Container's getter for MonthlyAnalyticsNewV1.
     * @return MonthlyAnalyticsNewV1
     */
    public ViewObjectImpl getMonthlyAnalyticsNewV1() {
        return (ViewObjectImpl)findViewObject("MonthlyAnalyticsNewV1");
    }

    /**
     * Container's getter for YearlyChartV1.
     * @return YearlyChartV1
     */
    public YearlyChartVVOImpl getYearlyChartV1() {
        return (YearlyChartVVOImpl)findViewObject("YearlyChartV1");
    }
}
