package oracle.project.AssetManagement.uiview;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 20 17:49:59 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MonthlyAnalyticsDebtVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Touser {
            public Object get(MonthlyAnalyticsDebtVVORowImpl obj) {
                return obj.getTouser();
            }

            public void put(MonthlyAnalyticsDebtVVORowImpl obj, Object value) {
                obj.setTouser((String)value);
            }
        },
        SumLentItem {
            public Object get(MonthlyAnalyticsDebtVVORowImpl obj) {
                return obj.getSumLentItem();
            }

            public void put(MonthlyAnalyticsDebtVVORowImpl obj, Object value) {
                obj.setSumLentItem((Number)value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MonthlyAnalyticsDebtVVORowImpl object);

        public abstract void put(MonthlyAnalyticsDebtVVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TOUSER = AttributesEnum.Touser.index();
    public static final int SUMLENTITEM = AttributesEnum.SumLentItem.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MonthlyAnalyticsDebtVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Touser.
     * @return the Touser
     */
    public String getTouser() {
        return (String)getAttributeInternal(TOUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Touser.
     * @param value value to set the  Touser
     */
    public void setTouser(String value) {
        setAttributeInternal(TOUSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SumLentItem.
     * @return the SumLentItem
     */
    public Number getSumLentItem() {
        return (Number)getAttributeInternal(SUMLENTITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SumLentItem.
     * @param value value to set the  SumLentItem
     */
    public void setSumLentItem(Number value) {
        setAttributeInternal(SUMLENTITEM, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
