package oracle.project.AssetManagement.uiview;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 20 15:04:49 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MonthlyVORowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MonthlyVORowImpl() {
    }
}
