package oracle.project.AssetManagement.uiview;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 26 14:14:58 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MonthlyAnalyticsNewVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MonthlyAnalyticsNewVVOImpl() {
    }
}
