package oracle.project.AssetManagement.uiview;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 20 17:57:33 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MonthlyAnalyticsBookLVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Userid {
            public Object get(MonthlyAnalyticsBookLVVORowImpl obj) {
                return obj.getUserid();
            }

            public void put(MonthlyAnalyticsBookLVVORowImpl obj,
                            Object value) {
                obj.setUserid((String)value);
            }
        },
        LentItem {
            public Object get(MonthlyAnalyticsBookLVVORowImpl obj) {
                return obj.getLentItem();
            }

            public void put(MonthlyAnalyticsBookLVVORowImpl obj,
                            Object value) {
                obj.setLentItem((String)value);
            }
        },
        TransactionType {
            public Object get(MonthlyAnalyticsBookLVVORowImpl obj) {
                return obj.getTransactionType();
            }

            public void put(MonthlyAnalyticsBookLVVORowImpl obj,
                            Object value) {
                obj.setTransactionType((String)value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MonthlyAnalyticsBookLVVORowImpl object);

        public abstract void put(MonthlyAnalyticsBookLVVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int USERID = AttributesEnum.Userid.index();
    public static final int LENTITEM = AttributesEnum.LentItem.index();
    public static final int TRANSACTIONTYPE =
        AttributesEnum.TransactionType.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MonthlyAnalyticsBookLVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Userid.
     * @return the Userid
     */
    public String getUserid() {
        return (String)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Userid.
     * @param value value to set the  Userid
     */
    public void setUserid(String value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LentItem.
     * @return the LentItem
     */
    public String getLentItem() {
        return (String)getAttributeInternal(LENTITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LentItem.
     * @param value value to set the  LentItem
     */
    public void setLentItem(String value) {
        setAttributeInternal(LENTITEM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransactionType.
     * @return the TransactionType
     */
    public String getTransactionType() {
        return (String)getAttributeInternal(TRANSACTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransactionType.
     * @param value value to set the  TransactionType
     */
    public void setTransactionType(String value) {
        setAttributeInternal(TRANSACTIONTYPE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
