package oracle.project.AssetManagement.uiview;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 20 17:49:59 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MonthlyAnalyticsDebtVVODefImpl extends ViewDefImpl {
    public MonthlyAnalyticsDebtVVODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public MonthlyAnalyticsDebtVVODefImpl() {
    }
}
