package oracle.project.AssetManagement.uiview;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 26 14:14:58 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MonthlyAnalyticsNewVVORowImpl extends ViewRowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MonthlyAnalyticsNewVVORowImpl() {
    }
}
