package oracle.project.AssetManagement.uiview;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 20 15:04:49 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MonthlyVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MonthlyVOImpl() {
    }
}
