package oracle.project.AssetManagement.uiview;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 19 19:52:51 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ViewObjVODefImpl extends ViewDefImpl {
    public ViewObjVODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public ViewObjVODefImpl() {
    }
}
