package oracle.project.AssetManagement.uiview;

import oracle.jbo.domain.Date;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 20 23:11:52 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class YearlyAnalyticsVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        TransactionId {
            public Object get(YearlyAnalyticsVVORowImpl obj) {
                return obj.getTransactionId();
            }

            public void put(YearlyAnalyticsVVORowImpl obj, Object value) {
                obj.setTransactionId((String)value);
            }
        },
        TransactionType {
            public Object get(YearlyAnalyticsVVORowImpl obj) {
                return obj.getTransactionType();
            }

            public void put(YearlyAnalyticsVVORowImpl obj, Object value) {
                obj.setTransactionType((String)value);
            }
        },
        Userid {
            public Object get(YearlyAnalyticsVVORowImpl obj) {
                return obj.getUserid();
            }

            public void put(YearlyAnalyticsVVORowImpl obj, Object value) {
                obj.setUserid((String)value);
            }
        },
        DueDate {
            public Object get(YearlyAnalyticsVVORowImpl obj) {
                return obj.getDueDate();
            }

            public void put(YearlyAnalyticsVVORowImpl obj, Object value) {
                obj.setDueDate((Date)value);
            }
        },
        LentItem {
            public Object get(YearlyAnalyticsVVORowImpl obj) {
                return obj.getLentItem();
            }

            public void put(YearlyAnalyticsVVORowImpl obj, Object value) {
                obj.setLentItem((String)value);
            }
        },
        CreationDate {
            public Object get(YearlyAnalyticsVVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(YearlyAnalyticsVVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        },
        Touser {
            public Object get(YearlyAnalyticsVVORowImpl obj) {
                return obj.getTouser();
            }

            public void put(YearlyAnalyticsVVORowImpl obj, Object value) {
                obj.setTouser((String)value);
            }
        },
        Quantity {
            public Object get(YearlyAnalyticsVVORowImpl obj) {
                return obj.getQuantity();
            }

            public void put(YearlyAnalyticsVVORowImpl obj, Object value) {
                obj.setQuantity((String)value);
            }
        },
        Status {
            public Object get(YearlyAnalyticsVVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(YearlyAnalyticsVVORowImpl obj, Object value) {
                obj.setStatus((String)value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(YearlyAnalyticsVVORowImpl object);

        public abstract void put(YearlyAnalyticsVVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int TRANSACTIONID =
        AttributesEnum.TransactionId.index();
    public static final int TRANSACTIONTYPE =
        AttributesEnum.TransactionType.index();
    public static final int USERID = AttributesEnum.Userid.index();
    public static final int DUEDATE = AttributesEnum.DueDate.index();
    public static final int LENTITEM = AttributesEnum.LentItem.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int TOUSER = AttributesEnum.Touser.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int STATUS = AttributesEnum.Status.index();

    /**
     * This is the default constructor (do not remove).
     */
    public YearlyAnalyticsVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute TransactionId.
     * @return the TransactionId
     */
    public String getTransactionId() {
        return (String)getAttributeInternal(TRANSACTIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransactionId.
     * @param value value to set the  TransactionId
     */
    public void setTransactionId(String value) {
        setAttributeInternal(TRANSACTIONID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TransactionType.
     * @return the TransactionType
     */
    public String getTransactionType() {
        return (String)getAttributeInternal(TRANSACTIONTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TransactionType.
     * @param value value to set the  TransactionType
     */
    public void setTransactionType(String value) {
        setAttributeInternal(TRANSACTIONTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Userid.
     * @return the Userid
     */
    public String getUserid() {
        return (String)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Userid.
     * @param value value to set the  Userid
     */
    public void setUserid(String value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DueDate.
     * @return the DueDate
     */
    public Date getDueDate() {
        return (Date)getAttributeInternal(DUEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DueDate.
     * @param value value to set the  DueDate
     */
    public void setDueDate(Date value) {
        setAttributeInternal(DUEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LentItem.
     * @return the LentItem
     */
    public String getLentItem() {
        return (String)getAttributeInternal(LENTITEM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LentItem.
     * @param value value to set the  LentItem
     */
    public void setLentItem(String value) {
        setAttributeInternal(LENTITEM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate.
     * @param value value to set the  CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Touser.
     * @return the Touser
     */
    public String getTouser() {
        return (String)getAttributeInternal(TOUSER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Touser.
     * @param value value to set the  Touser
     */
    public void setTouser(String value) {
        setAttributeInternal(TOUSER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Quantity.
     * @return the Quantity
     */
    public String getQuantity() {
        return (String)getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Quantity.
     * @param value value to set the  Quantity
     */
    public void setQuantity(String value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Status.
     * @return the Status
     */
    public String getStatus() {
        return (String)getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Status.
     * @param value value to set the  Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
