package oracle.project.AssetManagement.uiview;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 26 21:35:05 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class YearlyChartVVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Userid {
            public Object get(YearlyChartVVORowImpl obj) {
                return obj.getUserid();
            }

            public void put(YearlyChartVVORowImpl obj, Object value) {
                obj.setUserid((String)value);
            }
        },
        Lent {
            public Object get(YearlyChartVVORowImpl obj) {
                return obj.getLent();
            }

            public void put(YearlyChartVVORowImpl obj, Object value) {
                obj.setLent((Number)value);
            }
        },
        Owe {
            public Object get(YearlyChartVVORowImpl obj) {
                return obj.getOwe();
            }

            public void put(YearlyChartVVORowImpl obj, Object value) {
                obj.setOwe((Number)value);
            }
        };
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(YearlyChartVVORowImpl object);

        public abstract void put(YearlyChartVVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() +
                AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int USERID = AttributesEnum.Userid.index();
    public static final int LENT = AttributesEnum.Lent.index();
    public static final int OWE = AttributesEnum.Owe.index();

    /**
     * This is the default constructor (do not remove).
     */
    public YearlyChartVVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Userid.
     * @return the Userid
     */
    public String getUserid() {
        return (String)getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Userid.
     * @param value value to set the  Userid
     */
    public void setUserid(String value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Lent.
     * @return the Lent
     */
    public Number getLent() {
        return (Number)getAttributeInternal(LENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Lent.
     * @param value value to set the  Lent
     */
    public void setLent(Number value) {
        setAttributeInternal(LENT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Owe.
     * @return the Owe
     */
    public Number getOwe() {
        return (Number)getAttributeInternal(OWE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Owe.
     * @param value value to set the  Owe
     */
    public void setOwe(Number value) {
        setAttributeInternal(OWE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) &&
            (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index -
                AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
