package oracle.project.AssetManagement.uiview;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 20 23:00:14 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class YearlyAnalyticsBookOVVODefImpl extends ViewDefImpl {
    public YearlyAnalyticsBookOVVODefImpl(String name) {
        super(name);
    }

    /**
     * This is the default constructor (do not remove).
     */
    public YearlyAnalyticsBookOVVODefImpl() {
    }
}
