package oracle.project.AssetManagement.uiview;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 20 23:11:52 IST 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class YearlyAnalyticsVVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public YearlyAnalyticsVVOImpl() {
    }

    /**
     * Returns the variable value for m_user.
     * @return variable value for m_user
     */
    public String getm_user() {
        return (String)ensureVariableManager().getVariableValue("m_user");
    }

    /**
     * Sets <code>value</code> for variable m_user.
     * @param value value to bind as m_user
     */
    public void setm_user(String value) {
        ensureVariableManager().setVariableValue("m_user", value);
    }


}
